name: Counsler outreach
description: Counsler outreach is a platform were Mental health professioal 
can donate their time to people who can not afford the help.

publish_to: 'none'

version: 1.0.0+1

enviroment:
  sdk: ">= 2.16.0  <3.3.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:

  fonts:
